import { randomUUID } from 'node:crypto';
import { db, audit, transaction } from './db.mjs';
export function redirectPath(value) {
  if (
    typeof value !== 'string' ||
    value.length > 1000 ||
    !/^\/[A-Za-z0-9/_~.-]+$/.test(value) ||
    value.includes('//')
  )
    throw new Error(
      'Use a site path such as /old-post/. Queries and external URLs are not supported.',
    );
  let decoded;
  try {
    decoded = decodeURIComponent(value);
  } catch {
    throw new Error('Invalid URL encoding.');
  }
  if (
    /[%\\?#\s\x00-\x1f]/.test(decoded) ||
    decoded.split('/').some((s) => s === '.' || s === '..') ||
    /%2f/i.test(value)
  )
    throw new Error('Use a plain URL path without traversal or encoded separators.');
  return value;
}
export function listRedirects() {
  return db
    .prepare('SELECT * FROM redirects ORDER BY source')
    .all()
    .map((row) => ({
      id: String(row.id),
      source: String(row.source),
      destination: String(row.destination),
      status: Number(row.status),
      enabled: Number(row.enabled),
      created_at: String(row.created_at),
      ready:
        !row.destination.startsWith('/blog/') ||
        !!db
          .prepare(
            "SELECT id FROM posts WHERE ? = '/blog/' || slug || '/' AND published_version IS NOT NULL",
          )
          .get(row.destination),
    }));
}
export function saveRedirect(id, input, actor) {
  const source = redirectPath(input.from),
    destination = redirectPath(input.to);
  if (source === destination) throw new Error('Old and new URLs must be different.');
  const status = Number(input.status ?? 301);
  if (![301, 302, 307, 308].includes(status)) throw new Error('Choose a valid redirect status.');
  const enabled = input.enabled !== false;
  return transaction(() => {
    if (id && !db.prepare('SELECT id FROM redirects WHERE id=?').get(id))
      throw new Error('Redirect not found.');
    if (db.prepare('SELECT id FROM redirects WHERE source=? AND id!=?').get(source, id || ''))
      throw new Error('This old URL already has a redirect.');
    const others = listRedirects().filter((r) => r.id !== id);
    if (others.some((r) => r.source === destination || r.destination === source))
      throw new Error(
        'Redirect chains and loops are not allowed. Point old URLs directly to the final page.',
      );
    if (db.prepare("SELECT id FROM posts WHERE ? = '/blog/' || slug || '/'").get(source))
      throw new Error('The old URL belongs to an existing ABS post.');
    const key = id || randomUUID();
    db.prepare(
      'INSERT INTO redirects(id,source,destination,status,enabled,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET source=excluded.source,destination=excluded.destination,status=excluded.status,enabled=excluded.enabled',
    ).run(key, source, destination, status, enabled ? 1 : 0, new Date().toISOString());
    audit(actor, 'redirect-saved', key);
    return { id: key };
  });
}
export function deleteRedirect(id, actor) {
  db.prepare('DELETE FROM redirects WHERE id=?').run(id);
  audit(actor, 'redirect-deleted', id);
}
export function exportRedirects(format) {
  const all = listRedirects();
  const rows = all.filter((r) => r.enabled && r.ready);
  const mappings = rows.map((r) => ({ from: r.source, to: r.destination, status: r.status }));
  const warning =
    '# Generated by ABS. Apply on the website server; exporting does not activate redirects.\n';
  if (format === 'json') return JSON.stringify(mappings, null, 2) + '\n';
  if (format === 'nginx')
    return (
      warning +
      rows
        .map((r) => `location = ${r.source} { return ${r.status} ${r.destination}$is_args$args; }`)
        .join('\n') +
      '\n'
    );
  if (format === 'apache')
    return (
      warning +
      rows
        .map(
          (r) =>
            `RedirectMatch ${r.status} ^${r.source.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$ ${r.destination}`,
        )
        .join('\n') +
      '\n'
    );
  if (format === 'netlify')
    return warning + rows.map((r) => `${r.source} ${r.destination} ${r.status}!`).join('\n') + '\n';
  throw new Error('Unknown export format.');
}
